run:
  skip-dirs:
    - mocks
    - pkg/testfunc
    - cmd/testing
    - ../../
  skip-files:
    - ".*_test.go$"
  go: "1.21"

linters:
  enable:
    - funlen
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - ireturn
    - testpackage
    - varnamelen
    - wastedassign
    - whitespace
