basePath: /api/v1
definitions:
  echo.Map:
    additionalProperties: true
    type: object
info:
  contact: {}
  title: stori_challenge
  version: 0.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: Return a json content with a welcome message
      produces:
      - application/json
      responses:
        "200":
          description: Demo data
          schema:
            type: string
        "500":
          description: Something unidentified has occurred
      summary: Gets a json welcome message
      tags:
      - initial
  /analyze:
    post:
      description: Analyze a transactions file and send an email with generated data
      responses:
        "200":
          description: Confirmation message
          schema:
            $ref: '#/definitions/echo.Map'
        "500":
          description: Something unidentified has occurred
      summary: Analyze a transactions file
      tags:
      - transaction_analyzer
swagger: "2.0"
